apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sds6lj848-python
  janus-idp.io/tekton: sds6lj848-python
  backstage.io/kubernetes-id: sds6lj848-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sds6lj848-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
