apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sds6lj848-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sds6lj848-python 
  name: sds6lj848-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sds6lj848-python 
